name: Node.js CI

on:
  push: 
    branches: 
     - main
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - name: checkout repo.
        uses: actions/checkout@v2

      - name: install dependencies.
        run: npm install
        
      - name: running the app.
        run: npm start &

      - name: run test suite.
        run: npm test

  start-server:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: app/
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: npm install

      - name: start server
        run: npm start &
      
      - name: conditional step.
        run: echo "this step only runs on the main branch"
        if: github.ref == 'refs/heads/main'
      
      - name: print the secrets.
        run: echo "SECRET_VALUE_A=${{secrets.SECRET_VALUE_A}}"
      
      - name: conditional secret.
        if: env.SECRET_VALUE == 'A'
        run: echo "SECRET_VALUE_A is equal to A" 
        env:
          SECRET_VALUE: secrets.SECRET_VALUE_A