name: Node.js CI

on:
  push: 
    branches: 
     - main
  workflow_dispatch: 

jobs:
  install_node_dependencies:
    uses: widolite/workflows/.github/workflows/common-step-build-node.yml@main
  test:
    services:
      webserver:
        image: nginx:latest
        ports:
          - 8080:80
    defaults:
      run:
        working-directory: app/
    runs-on: ubuntu-latest
    needs: install_node_dependencies
    steps:
      - uses: actions/checkout@v4

      - name: getting node modules
        uses: actions/download-artifact@v3
        with:
          name: modules   
      
      - name: running the app.
        run: npm start &

      - name: run test suite.
        run: npm test

      - name: testing nginx service running as sidecard container.
        run: curl -X GET http://127.0.0.1:8080
  start-server:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: app/
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: npm install

      - name: start server
        run: npm start &
      
      - name: conditional step.
        run: echo "this step only runs on the main branch"
        if: github.ref == 'refs/heads/main'
      
      - name: print the secrets.
        run: echo "SECRET_VALUE_A=${{secrets.SECRET_VALUE_A}}"
      
      - name: conditional secret.
        if: env.SECRET_VALUE == 'A'
        run: echo "SECRET_VALUE_A is equal to A" 
        env:
          SECRET_VALUE: ${{secrets.SECRET_VALUE_A}}